import type { Tag } from "@torigen/mounter";

const models: Tag[] = [
  { id: "artbook", label: "Artbook" },
  { id: "cartoon", label: "Cartoon" },
  { id: "comic", label: "Comic" },
  { id: "doujinshi", label: "Doujinshi" },
  { id: "imageset", label: "Imageset" },
  { id: "manga", label: "Manga" },
  { id: "manhua", label: "Manhua" },
  { id: "manhwa", label: "Manhwa" },
  { id: "webtoon", label: "Webtoon" },
  { id: "western", label: "Western" },
  { id: "4_koma", label: "4-Koma" },
  { id: "oneshot", label: "Oneshot" },
];

const ratings: Tag[] = [
  { id: "shoujo", label: "Shoujo" },
  { id: "shounen", label: "Shounen" },
  { id: "josei", label: "Josei" },
  { id: "seinen", label: "Seinen" },
  { id: "yuri", label: "Yuri" },
  { id: "yaoi", label: "Yaoi" },
  { id: "bara", label: "Bara" },
  { id: "kodomo", label: "Kodomo" },
  { id: "old_people", label: "Old People" },
  { id: "non_human", label: "Non-Human" },
];

const matureTags: Tag[] = [
  { id: "gore", label: "Gore" },
  { id: "bloody", label: "Bloody" },
  { id: "violence", label: "Violence" },
  { id: "ecchi", label: "Ecchi" },
  { id: "adult", label: "Adult" },
  { id: "mature", label: "Mature" },
  { id: "smut", label: "Smut" },
  { id: "hentai", label: "Hentai" },
];

const genres: Tag[] = [
  { id: "action", label: "Action" },
  { id: "adaptation", label: "Adaptation" },
  { id: "adventure", label: "Adventure" },
  { id: "age_gap", label: "Age Gap" },
  { id: "aliens", label: "Aliens" },
  { id: "animals", label: "Animals" },
  { id: "anthology", label: "Anthology" },
  { id: "beasts", label: "Beasts" },
  { id: "bodyswap", label: "Bodyswap" },
  { id: "boys", label: "Boys" },
  { id: "cars", label: "Cars" },
  { id: "cheating_infidelity", label: "Cheating/Infidelity" },
  { id: "childhood_friends", label: "Childhood Friends" },
  { id: "college_life", label: "College Life" },
  { id: "comedy", label: "Comedy" },
  { id: "contest_winning", label: "Contest Winning" },
  { id: "cooking", label: "Cooking" },
  { id: "crime", label: "Crime" },
  { id: "crossdressing", label: "Crossdressing" },
  { id: "delinquents", label: "Delinquents" },
  { id: "dementia", label: "Dementia" },
  { id: "demons", label: "Demons" },
  { id: "drama", label: "Drama" },
  { id: "dungeons", label: "Dungeons" },
  { id: "emperor_daughte", label: "Emperor's Daughter" },
  { id: "fantasy", label: "Fantasy" },
  { id: "fan_colored", label: "Fan Colored" },
  { id: "fetish", label: "Fetish" },
  { id: "full_color", label: "Full Color" },
  { id: "game", label: "Game" },
  { id: "gender_bender", label: "Gender Bender" },
  { id: "genderswap", label: "Genderswap" },
  { id: "ghosts", label: "Ghosts" },
  { id: "girls", label: "Girls" },
  { id: "gyaru", label: "Gyaru" },
  { id: "harem", label: "Harem" },
  { id: "harlequin", label: "Harlequin" },
  { id: "historical", label: "Historical" },
  { id: "horror", label: "Horror" },
  { id: "incest", label: "Incest" },
  { id: "isekai", label: "Isekai" },
  { id: "kids", label: "Kids" },
  { id: "magic", label: "Magic" },
  { id: "magical_girls", label: "Magical Girls" },
  { id: "martial_arts", label: "Martial Arts" },
  { id: "mecha", label: "Mecha" },
  { id: "medical", label: "Medical" },
  { id: "military", label: "Military" },
  { id: "monster_girls", label: "Monster Girls" },
  { id: "monsters", label: "Monsters" },
  { id: "music", label: "Music" },
  { id: "mystery", label: "Mystery" },
  { id: "netorare", label: "Netorare" },
  { id: "ninja", label: "Ninja" },
  { id: "office_workers", label: "Office Workers" },
  { id: "omegaverse", label: "Omegaverse" },
  { id: "parody", label: "Parody" },
  { id: "philosophical", label: "Philosophical" },
  { id: "police", label: "Police" },
  { id: "post_apocalyptic", label: "Post-Apocalyptic" },
  { id: "psychological", label: "Psychological" },
  { id: "regression", label: "Regression" },
  { id: "reincarnation", label: "Reincarnation" },
  { id: "reverse_harem", label: "Reverse Harem" },
  { id: "revenge", label: "Revenge" },
  { id: "reverse_isekai", label: "Reverse Isekai" },
  { id: "romance", label: "Romance" },
  { id: "royal_family", label: "Royal Family" },
  { id: "royalty", label: "Royalty" },
  { id: "samurai", label: "Samurai" },
  { id: "school_life", label: "School Life" },
  { id: "sci_fi", label: "Sci-Fi" },
  { id: "shoujo_ai", label: "Shoujo Ai" },
  { id: "shounen_ai", label: "Shounen Ai" },
  { id: "showbiz", label: "Showbiz" },
  { id: "slice_of_life", label: "Slice of Life" },
  { id: "sm_bdsm", label: "SM/BDSM" },
  { id: "space", label: "Space" },
  { id: "sports", label: "Sports" },
  { id: "super_power", label: "Super Power" },
  { id: "superhero", label: "Superhero" },
  { id: "supernatural", label: "Supernatural" },
  { id: "survival", label: "Survival" },
  { id: "thriller", label: "Thriller" },
  { id: "time_travel", label: "Time Travel" },
  { id: "tower_climbing", label: "Tower Climbing" },
  { id: "traditional_games", label: "Traditional Games" },
  { id: "tragedy", label: "Tragedy" },
  { id: "transmigration", label: "Transmigration" },
  { id: "vampires", label: "Vampires" },
  { id: "villainess", label: "Villainess" },
  { id: "video_games", label: "Video Games" },
  { id: "virtual_reality", label: "Virtual Reality" },
  { id: "wuxia", label: "Wuxia" },
  { id: "xianxia", label: "Xianxia" },
  { id: "xuanhuan", label: "Xuanhuan" },
  { id: "yakuzas", label: "Yakuzas" },
  { id: "zombies", label: "Zombies" },
];

const transl_lang_tags: Tag[] = [
  { id: "af", label: "Afrikaans" },
  { id: "ar", label: "Arabic" },
  { id: "az", label: "Azerbaijani" },
  { id: "eu", label: "Basque" },
  { id: "be", label: "Belarusian" },
  { id: "bn", label: "Bengali" },
  { id: "bs", label: "Bosnian" },
  { id: "bg", label: "Bulgarian" },
  { id: "my", label: "Burmese" },
  { id: "km", label: "Cambodian" },
  { id: "ceb", label: "Cebuano" },
  { id: "zh", label: "Chinese" },
  { id: "zh_hk", label: "Chinese (粵)" },
  { id: "zh_tw", label: "Chinese (繁)" },
  { id: "hr", label: "Croatian" },
  { id: "cs", label: "Czech" },
  { id: "da", label: "Danish" },
  { id: "nl", label: "Dutch" },
  { id: "en", label: "English" },
  { id: "en_us", label: "English (US)" },
  { id: "eo", label: "Esperanto" },
  { id: "et", label: "Estonian" },
  { id: "fil", label: "Filipino" },
  { id: "fi", label: "Finnish" },
  { id: "fr", label: "French" },
  { id: "ka", label: "Georgian" },
  { id: "de", label: "German" },
  { id: "el", label: "Greek" },
  { id: "gu", label: "Gujarati" },
  { id: "ht", label: "Haitian Creole" },
  { id: "he", label: "Hebrew" },
  { id: "hi", label: "Hindi" },
  { id: "hu", label: "Hungarian" },
  { id: "is", label: "Icelandic" },
  { id: "ig", label: "Igbo" },
  { id: "id", label: "Indonesian" },
  { id: "ga", label: "Irish" },
  { id: "it", label: "Italian" },
  { id: "ja", label: "Japanese" },
  { id: "jv", label: "Javanese" },
  { id: "kk", label: "Kazakh" },
  { id: "ko", label: "Korean" },
  { id: "lo", label: "Lao" },
  { id: "lv", label: "Latvian" },
  { id: "lt", label: "Lithuanian" },
  { id: "ms", label: "Malay" },
  { id: "ml", label: "Malayalam" },
  { id: "mo", label: "Moldovan" },
  { id: "mn", label: "Mongolian" },
  { id: "ne", label: "Nepali" },
  { id: "no", label: "Norwegian" },
  { id: "ps", label: "Pashto" },
  { id: "fa", label: "Persian" },
  { id: "pl", label: "Polish" },
  { id: "pt", label: "Portuguese" },
  { id: "pt_br", label: "Portuguese (BR)" },
  { id: "pt_pt", label: "Portuguese (PT)" },
  { id: "ro", label: "Romanian" },
  { id: "ru", label: "Russian" },
  { id: "sr", label: "Serbian" },
  { id: "si", label: "Sinhalese" },
  { id: "sk", label: "Slovak" },
  { id: "es", label: "Spanish" },
  { id: "es_419", label: "Spanish (LA)" },
  { id: "ta", label: "Tamil" },
  { id: "te", label: "Telugu" },
  { id: "th", label: "Thai" },
  { id: "ti", label: "Tigrinya" },
  { id: "tr", label: "Turkish" },
  { id: "uk", label: "Ukrainian" },
  { id: "ur", label: "Urdu" },
  { id: "vi", label: "Vietnamese" },
  { id: "yo", label: "Yoruba" },
  { id: "zu", label: "Zulu" },
  { id: "_t", label: "Other" },
];

const orig_lang_tags: Tag[] = [
  { id: "af", label: "Afrikaans" },
  { id: "sq", label: "Albanian" },
  { id: "am", label: "Amharic" },
  { id: "ar", label: "Arabic" },
  { id: "hy", label: "Armenian" },
  { id: "az", label: "Azerbaijani" },
  { id: "be", label: "Belarusian" },
  { id: "bn", label: "Bengali" },
  { id: "bs", label: "Bosnian" },
  { id: "bg", label: "Bulgarian" },
  { id: "my", label: "Burmese" },
  { id: "km", label: "Cambodian" },
  { id: "ceb", label: "Cebuano" },
  { id: "zh", label: "Chinese" },
  { id: "zh_hk", label: "Chinese (粵)" },
  { id: "zh_tw", label: "Chinese (繁)" },
  { id: "hr", label: "Croatian" },
  { id: "nl", label: "Dutch" },
  { id: "en", label: "English" },
  { id: "en_us", label: "English (US)" },
  { id: "fil", label: "Filipino" },
  { id: "fi", label: "Finnish" },
  { id: "fr", label: "French" },
  { id: "de", label: "German" },
  { id: "el", label: "Greek" },
  { id: "hi", label: "Hindi" },
  { id: "hu", label: "Hungarian" },
  { id: "ig", label: "Igbo" },
  { id: "id", label: "Indonesian" },
  { id: "it", label: "Italian" },
  { id: "ja", label: "Japanese" },
  { id: "jv", label: "Javanese" },
  { id: "kn", label: "Kannada" },
  { id: "kk", label: "Kazakh" },
  { id: "ko", label: "Korean" },
  { id: "ku", label: "Kurdish" },
  { id: "ky", label: "Kyrgyz" },
  { id: "lt", label: "Lithuanian" },
  { id: "lb", label: "Luxembourgish" },
  { id: "ms", label: "Malay" },
  { id: "mn", label: "Mongolian" },
  { id: "fa", label: "Persian" },
  { id: "pl", label: "Polish" },
  { id: "pt", label: "Portuguese" },
  { id: "pt_br", label: "Portuguese (BR)" },
  { id: "ru", label: "Russian" },
  { id: "sr", label: "Serbian" },
  { id: "sn", label: "Shona" },
  { id: "si", label: "Sinhalese" },
  { id: "es", label: "Spanish" },
  { id: "es_419", label: "Spanish (LA)" },
  { id: "tg", label: "Tajik" },
  { id: "th", label: "Thai" },
  { id: "tr", label: "Turkish" },
  { id: "uk", label: "Ukrainian" },
  { id: "ur", label: "Urdu" },
  { id: "vi", label: "Vietnamese" },
  { id: "yo", label: "Yoruba" },
  { id: "zu", label: "Zulu" },
  { id: "_t", label: "Other" },
];

export const lang_filters = {
  origin_lang: orig_lang_tags,
  transl_lang: transl_lang_tags,
};

export const tag_filters = {
  models: models,
  ratings: ratings,
  mature: matureTags,
  genres: genres,
};

export const chap_filters = [
  { id: "1-9", label: "1-9" },
  { id: "10-29", label: "10-29" },
  { id: "30-99", label: "30-99" },
  { id: "100-199", label: "100-199" },
  { id: "200", label: "200+" },
  { id: "100", label: "100+" },
  { id: "10", label: "10+" },
  { id: "1", label: "1+" },
];
